version: 2.1
 
orbs:
  heroku: circleci/heroku@1.2.2
 
workflows:
  heroku_deploy:
    jobs:
      - build-and-test
 
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
            name: Install dependencies
            command: sudo pip install -r requirements.txt
      - run: 
            name: Run unmocked tests
            command: python ./tests/unmocked_tests.py
      - run:
            name: Run mocked tests
            command: python ./tests/mocked_tests.py