version: 2.1
 
orbs:
  heroku: circleci/heroku@1.2.2
 
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
 
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: 
            command: python ./tests/unmocked_tests.py
            name: Run unmocked tests
      - run:
            command: python ./tests/mocked_tests.py
            name: Run mocked tests